---
title: "260Project"
output: html_document
---

```{r}
game <- read_csv("C:/Users/Shimin/Desktop/BST260/Project/bgg_db_2017_04.csv")
```

# Data Cleaning 
```{r}
missing(game) #F
## ABNORMAL
# avg_time
0 %in% game$avg_time  #T
length(which(game$avg_time==0))  #82

# min_players + max_players
0 %in% game$min_players  #T
length(which(game$min_players==0))  #14
0 %in% game$max_players  #T
length(which(game$max_players==0))  #26
length(which(game$min_players>0 & game$max_players==0))  #16
length(which(game$min_players==0 & game$max_players==0))  #10

# min_time + max_time
0 %in% game$min_time  #T
length(which(game$min_time==0))  #87
0 %in% game$max_time  #T
length(which(game$max_time==0))  #121

# year
range(game$year)  #-3000  2018
which(game$year < 0)  #104 1036
which(game$year > 2017) #3791

# weight
range(game$weight)  #0.0000 4.9048
length(which(game$weight==0))  #3

## NORMAL
# avg_rating
range(game$avg_rating)  #5.73429 9.33167
range(game$geek_rating)  #5.62627 8.48904

# num_votes
range(game$num_votes)  #47 68505

# age
range(game$age)  #0 42
length(which(game$age==0))  #252

# owned
range(game$owned)  #12 96783
```



```{r}
library(ggplot2)
library(dplyr)
data %>% ggplot(aes(geek_rating, avg_rating)) +
  geom_point(alpha = 0.8) +
   geom_smooth()
```

```{r}
data %>% ggplot(aes(avg_time))+
  geom_histogram(bins = 100) 
```

```{r}
data %>% ggplot(aes(avg_time))+
  geom_histogram()+
  scale_x_continuous(trans = "log2") 
```

```{r}

```










