---
title: "Clean data code"
output: html_document
---

```{r}
#game <- read.csv(file = file.choose())

# min_players
game$min_players[1616] <- 1 
game$min_players[1962] <- 1 
game$min_players[2273] <- 1 
game$min_players[2408] <- 1 
game$min_players[2693] <- 1 
game$min_players[3332] <- 1 
game$min_players[3850] <- 1 
game$min_players[3902] <- 1 
game$min_players[4145] <- 1 
game$min_players[4247] <- 1 
game$min_players[4311] <- 1 
game$min_players[4442] <- 1 
game$min_players[4480] <- 1 
game$min_players[4815] <- 1 

# max_players
game$max_players[1616] <- NA
game$max_players[1962] <- NA
game$max_players[2273] <- NA
game$max_players[2408] <- NA
game$max_players[2687] <- 2
game$max_players[2739] <- 4
game$max_players[2818] <- 2
game$max_players[3332] <- 1
game$max_players[3356] <- 4
game$max_players[3570] <- 2
game$max_players[3724] <- 2
game$max_players[3875] <- 2
game$max_players[3902] <- NA
game$max_players[4016] <- 2
game$max_players[4145] <- NA
game$max_players[4241] <- 2
game$max_players[4354] <- 2
game$max_players[4437] <- 2
game$max_players[4442] <- NA
game$max_players[4480] <- NA
game$max_players[4504] <- 2
game$max_players[4528] <- 2
game$max_players[4540] <- 2
game$max_players[4795] <- 2
game$max_players[4815] <- NA
game$max_players[4988] <- 2

# weight
game$weight[1477] <- NA
game$weight[4381] <- NA
game$weight[4521] <- NA

# final check
length(which(game$min_players==0))  
length(which(game$max_players==0))  
length(which(game$weight==0)) 

# write txt and import txt
#write.table(game, file = "game_partclean_Shimin.txt", sep = "|", row.names = FALSE,
#            col.names = TRUE, quote = FALSE)

#newgame <- read.csv("game_partclean_Shimin.txt", header = T, sep = "|") 
```

11/21
Recode players as 3 new categorical variables taking values 0, 1.  (Shimin)
Single_player =1: min_players =1 
Multi_player =1: min_players >1 & min_players <= 4 (I think this will work - MZ)
Party_player =1: max_players >4 
Recode min_time (short,  medium, long) to be categorical (use interquartile range) (Shimin)
Recode weight into categorical variable: easy, medium, hard (use interquartile range) (Shimin)

```{r}
# Recode variables
library(dplyr)
game <- read.csv("https://raw.githubusercontent.com/lennku/boardgameproject/Yanying/bgg_clean_dat.csv", sep = "")
# recode players
game$single_player = 0
game$single_player[game$min_players == 1] = 1
game$multi_player = 0
game$multi_player[game$min_players > 1 & game$max_players <= 4] = 1
game$party_player = 0
game$party_player[game$max_players > 4] = 1
# recode min_time
# 0 = short,  1 = medium, 2 = long
quantile(game$min_time, na.rm = T) 
game$cate_mintime = 0
game$cate_mintime[game$min_time >= 30 & game$min_time <= 90] = 1
game$cate_mintime[game$min_time > 90] = 2
# recode avg_time
# 0 = short,  1 = medium, 2 = long
quantile(game$avg_time, na.rm = T)
game$cate_avgtime = 0
game$cate_avgtime[game$avg_time >= 30 & game$avg_time <= 120] = 1
game$cate_avgtime[game$avg_time > 120] = 2
# recode weight
# 0 = easy, 1 = medium, 2 = hard
quantile(game$weight, na.rm = T)
game$cate_weight = 0
game$cate_weight[game$weight >= 1.73885 & game$weight <= 2.8889] = 1
game$cate_weight[game$weight > 2.8889] = 2
# write csv and import csv
write.table(game, file = "game_recode.txt", sep = "|", row.names = FALSE,
            col.names = TRUE, quote = FALSE)
n <- read.csv("game_recode.txt", header = T, sep = "|") 
```




